### ISSUE TITLE
4.1 Release - Master TODO list

### ISSUE THREAD

**Issue by SammyK** [facebook/facebook-php-sdk-v4#136]
Thought it'd be good to compile everything we've been talking about for 4.1 into a master list. I'll keep it up-to-date and add/remove items if we need to.

Each of these could be a separate PR. It's more-or-less in the order we'll need to tackle them.

- [x] Create new branches for 4.0 and 4.1 per #103 - @gfosco 
- [x] Add docs to the repo - @gfosco 
- [x] Restructure files/namespaces per #132 & *update docs* - @yguedidi? are you taking care of this?
- [x] Refactor response/collection handling per #36 & *update docs* - @SammyK
- [x] Refactor request handling per #36 & *update docs* - @SammyK
- [x] Add batch support per #100 & *update docs* - @SammyK & @gfosco?
- [x] Refactor `GraphObject` and `GraphList` collection handling - @SammyK
- [x] Add pagination to `GraphList`
- [x] Add factories
- [x] Figure out better `$_SESSION` handling/extensibility per #44.
- [x] Add `FacebookFile` and `FacebookVideo`? for file uploads.
- [x] Add `PseudorandomStringGeneratorInterface` for overwriting random string generation
- [x] Add Travis CI per #10 and #94.
- [x] Make sure all documentation is up-to-date before releasing

Let's do this!

![](http://media.tumblr.com/519bffc9167e605c1ee109c0d09b0f88/tumblr_inline_n6kiugEB4V1s0kpdb.gif)

**Comment by SammyK** [comment]
Hey @gfosco!

I was thinking it might be a good idea to go head and pull in the stable 4.1/5.0-related PR's and update the docs to reflect the current state & tag 4.1 (or 5.0 if we go that route per #332).

The main PR's that are ready to pull in for 4.1/5.0 would be #335, #334, #330, & #307 (if you like @christhomas's suggestion).

I know I've proposed a some BC's like #320 but at this point I'd just like to get this bad boy released and we can roll all future BC's into the next `MAJOR` releases.

If we do that, that should clear out a bunch of the open issues and PR's related to 4.0 as well. :)

I'm going to try and make some time tomorrow to get the docs as up-to-date as possible if we're a go on the pending PR's! :)
